/* Generated By:JavaCC: Do not edit this line. compConstants.java */
package olc2.JAVACC;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface compConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ASIGNACION = 1;
  /** RegularExpression Id. */
  int PLUS = 2;
  /** RegularExpression Id. */
  int MINUS = 3;
  /** RegularExpression Id. */
  int MULTIPLY = 4;
  /** RegularExpression Id. */
  int DIVIDE = 5;
  /** RegularExpression Id. */
  int INCR = 6;
  /** RegularExpression Id. */
  int DECR = 7;
  /** RegularExpression Id. */
  int PR_PREGUNTA = 8;
  /** RegularExpression Id. */
  int PR_Fin_PREGUNTA = 9;
  /** RegularExpression Id. */
  int PR_TIPO = 10;
  /** RegularExpression Id. */
  int PR_Fin_TIPO = 11;
  /** RegularExpression Id. */
  int PR_IDPREGUNTA = 12;
  /** RegularExpression Id. */
  int PR_Fin_IDPREGUNTA = 13;
  /** RegularExpression Id. */
  int PR_ETIQUETA = 14;
  /** RegularExpression Id. */
  int PR_Fin_ETIQUETA = 15;
  /** RegularExpression Id. */
  int PR_SUGERIR = 16;
  /** RegularExpression Id. */
  int PR_Fin_SUGERIR = 17;
  /** RegularExpression Id. */
  int PR_CODIGO_PRE = 18;
  /** RegularExpression Id. */
  int PR_Fin_CODIGO_PRE = 19;
  /** RegularExpression Id. */
  int PR_CODIGO_POST = 20;
  /** RegularExpression Id. */
  int PR_Fin_CODIGO_POST = 21;
  /** RegularExpression Id. */
  int PR_RESTRINGIR = 22;
  /** RegularExpression Id. */
  int PR_Fin_RESTRINGIR = 23;
  /** RegularExpression Id. */
  int PR_RESTRINGIRMSN = 24;
  /** RegularExpression Id. */
  int PR_Fin_RESTRINGIRMSN = 25;
  /** RegularExpression Id. */
  int PR_REQUERIDO = 26;
  /** RegularExpression Id. */
  int PR_Fin_REQUERIDO = 27;
  /** RegularExpression Id. */
  int PR_REQUERIDOMSN = 28;
  /** RegularExpression Id. */
  int PR_Fin_REQUERIDOMSN = 29;
  /** RegularExpression Id. */
  int PR_PREDETERMINADO = 30;
  /** RegularExpression Id. */
  int PR_Fin_PREDETERMINADO = 31;
  /** RegularExpression Id. */
  int PR_APLICABLE = 32;
  /** RegularExpression Id. */
  int PR_Fin_APLICABLE = 33;
  /** RegularExpression Id. */
  int PR_LECTURA = 34;
  /** RegularExpression Id. */
  int PR_Fin_LECTURA = 35;
  /** RegularExpression Id. */
  int PR_CALCULO = 36;
  /** RegularExpression Id. */
  int PR_Fin_CALCULO = 37;
  /** RegularExpression Id. */
  int PR_REPETICION = 38;
  /** RegularExpression Id. */
  int PR_Fin_REPETICION = 39;
  /** RegularExpression Id. */
  int PR_MULTIMEDIA = 40;
  /** RegularExpression Id. */
  int PR_Fin_MULTIMEDIA = 41;
  /** RegularExpression Id. */
  int PR_APARIENCIA = 42;
  /** RegularExpression Id. */
  int PR_Fin_APARIENCIA = 43;
  /** RegularExpression Id. */
  int PR_PARAMETRO = 44;
  /** RegularExpression Id. */
  int PR_Fin_PARAMETRO = 45;
  /** RegularExpression Id. */
  int PR_GRUPO = 46;
  /** RegularExpression Id. */
  int PR_Fin_GRUPO = 47;
  /** RegularExpression Id. */
  int PR_CICLO = 48;
  /** RegularExpression Id. */
  int PR_Fin_CICLO = 49;
  /** RegularExpression Id. */
  int PR_L_OPCION = 50;
  /** RegularExpression Id. */
  int PR_Fin_OPCION = 51;
  /** RegularExpression Id. */
  int PR_L_CONFI = 52;
  /** RegularExpression Id. */
  int PR_Fin_CONFI = 53;
  /** RegularExpression Id. */
  int PR_NOMBRELISTA = 54;
  /** RegularExpression Id. */
  int PR_Fin_NOMBRELISTA = 55;
  /** RegularExpression Id. */
  int PR_NOMBRE = 56;
  /** RegularExpression Id. */
  int PR_Fin_NOMBRE = 57;
  /** RegularExpression Id. */
  int PR_TITULOFORM = 58;
  /** RegularExpression Id. */
  int PR_Fin_TITULOFORM = 59;
  /** RegularExpression Id. */
  int PR_IDFORM = 60;
  /** RegularExpression Id. */
  int PR_Fin_IDFORM = 61;
  /** RegularExpression Id. */
  int PR_ESTILO = 62;
  /** RegularExpression Id. */
  int PR_Fin_ESTILO = 63;
  /** RegularExpression Id. */
  int PR_IMPORTAR = 64;
  /** RegularExpression Id. */
  int PR_Fin_IMPORTAR = 65;
  /** RegularExpression Id. */
  int PR_CODIGO_PRINCIPAL = 66;
  /** RegularExpression Id. */
  int PR_Fin_CODIGO_PRINCIPAL = 67;
  /** RegularExpression Id. */
  int PR_CODIGO_GLOBAL = 68;
  /** RegularExpression Id. */
  int PR_Fin_CODIGO_GLOBAL = 69;
  /** RegularExpression Id. */
  int PR_texto = 70;
  /** RegularExpression Id. */
  int PR_entero = 71;
  /** RegularExpression Id. */
  int PR_decimal = 72;
  /** RegularExpression Id. */
  int PR_rango = 73;
  /** RegularExpression Id. */
  int PR_condicion = 74;
  /** RegularExpression Id. */
  int PR_fecha = 75;
  /** RegularExpression Id. */
  int PR_hora = 76;
  /** RegularExpression Id. */
  int PR_fechahora = 77;
  /** RegularExpression Id. */
  int PR_seleccion_uno = 78;
  /** RegularExpression Id. */
  int PR_seleccion_multiple = 79;
  /** RegularExpression Id. */
  int PR_nota = 80;
  /** RegularExpression Id. */
  int PR_fichero = 81;
  /** RegularExpression Id. */
  int PR_calcular = 82;
  /** RegularExpression Id. */
  int PR_inicio_grupo = 83;
  /** RegularExpression Id. */
  int PR_finalizar_grupo = 84;
  /** RegularExpression Id. */
  int PR_iniciar_ciclo = 85;
  /** RegularExpression Id. */
  int PR_finalizar_ciclo = 86;
  /** RegularExpression Id. */
  int PR_MAYORQUE = 87;
  /** RegularExpression Id. */
  int PR_MENORQUE = 88;
  /** RegularExpression Id. */
  int EQ = 89;
  /** RegularExpression Id. */
  int LE = 90;
  /** RegularExpression Id. */
  int GE = 91;
  /** RegularExpression Id. */
  int NE = 92;
  /** RegularExpression Id. */
  int OR = 93;
  /** RegularExpression Id. */
  int AND = 94;
  /** RegularExpression Id. */
  int IDENTIFIER = 95;
  /** RegularExpression Id. */
  int ENTERO = 96;
  /** RegularExpression Id. */
  int DECIMAL = 97;
  /** RegularExpression Id. */
  int ETINI = 103;
  /** RegularExpression Id. */
  int POSI = 104;
  /** RegularExpression Id. */
  int ID = 105;
  /** RegularExpression Id. */
  int Numeral = 106;
  /** RegularExpression Id. */
  int Acor = 107;
  /** RegularExpression Id. */
  int ARRO = 108;
  /** RegularExpression Id. */
  int Ccor = 109;
  /** RegularExpression Id. */
  int Punto = 110;
  /** RegularExpression Id. */
  int PuntoP = 111;
  /** RegularExpression Id. */
  int Cualquiera = 112;
  /** RegularExpression Id. */
  int ETFIN = 113;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int INICIO_CAD = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"++\"",
    "\"--\"",
    "\"<pregunta>\"",
    "\"</pregunta>\"",
    "\"<tipo>\"",
    "\"</tipo>\"",
    "\"<idpregunta>\"",
    "\"</idpregunta>\"",
    "\"<etiqueta>\"",
    "\"</etiqueta>\"",
    "\"<sugerir>\"",
    "\"</sugerir>\"",
    "\"<codigo_pre>\"",
    "\"</codigo_pre>\"",
    "\"<codigo_post>\"",
    "\"</codigo_post>\"",
    "\"<restringir>\"",
    "\"</restringir>\"",
    "\"<restringirmsn>\"",
    "\"</restringirmsn>\"",
    "\"<requerido>\"",
    "\"</requerido>\"",
    "\"<requeridomsn>\"",
    "\"</requeridomsn>\"",
    "\"<predeterminado>\"",
    "\"</predeterminado>\"",
    "\"<aplicable>\"",
    "\"</aplicable>\"",
    "\"<lectura>\"",
    "\"</lectura>\"",
    "\"<calculo>\"",
    "\"</calculo>\"",
    "\"<repeticion>\"",
    "\"</repeticion>\"",
    "\"<multimedia>\"",
    "\"</multimedia>\"",
    "\"<apariencia>\"",
    "\"</apariencia>\"",
    "\"<parametro>\"",
    "\"</parametro>\"",
    "\"<grupo>\"",
    "\"</grupo>\"",
    "\"<ciclo>\"",
    "\"</ciclo>\"",
    "\"<l_opcion>\"",
    "\"</l_opcion>\"",
    "\"<l_config>\"",
    "\"</l_config>\"",
    "\"<nombre_lista>\"",
    "\"</nombre_lista>\"",
    "\"<nombre>\"",
    "\"</nombre>\"",
    "\"<titulo_formulario>\"",
    "\"</titulo_formulario>\"",
    "\"<idform>\"",
    "\"</idform>\"",
    "\"<estilo>\"",
    "\"</estilo>\"",
    "\"<importar>\"",
    "\"</importar>\"",
    "\"<codigo_principal>\"",
    "\"</codigo_principal>\"",
    "\"<codigo_global>\"",
    "\"</codigo_global>\"",
    "\"texto\"",
    "\"entero\"",
    "\"decimal\"",
    "\"rango\"",
    "\"condicion\"",
    "\"fecha\"",
    "\"hora\"",
    "\"fechahora\"",
    "\"selecciona_uno\"",
    "\"selecciona_multiple\"",
    "\"nota\"",
    "\"fichero\"",
    "\"calcular\"",
    "\"iniciar agrupacion\"",
    "\"finalizar agrupacion\"",
    "\"iniciar ciclo\"",
    "\"finalizar ciclo\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "<IDENTIFIER>",
    "<ENTERO>",
    "<DECIMAL>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\"/^\"",
    "<POSI>",
    "<ID>",
    "\"#\"",
    "\"[\"",
    "\"@\"",
    "\"]\"",
    "\".\"",
    "\"..\"",
    "<Cualquiera>",
    "\"^/\"",
  };

}
